version: '3'
services:
  api:
    image: flpos/rent-api
    ports:
      - 3000:3000
    links:
      - mongo
    environment:
      DB_URL: 'mongodb://${DB_ROOT-root}:${DB_PASS-abc123}@mongo:27017'
    build: .
  mongo:
    build: ./mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT-root}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS-abc123}
      MONGO_INITDB_DATABASE: rent
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ROOT-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS-abc123}
      ME_CONFIG_MONGODB_URL: 'mongodb://${DB_ROOT-root}:${DB_PASS-abc123}@mongo:27017'
